#!/bin/bash
INPUTFILE=$1
COUNTER="0"
LABELFILE="labelfile.txt"
LATEXINPUTLABELS="inputlabels.tex"
LBLROW="0"
LBLCOL="0"
MAXLBLROW="8"
MAXLBLCOL="5"
ZEROPOSX="100"
ZEROPOSY="10"
XPITCHSIZE1="17"
XPITCHSIZE2="35"
XPITCHSIZEB="10"
YPITCH="21"
MAXX="200"
MAXY="280"

LATEXTEMPLATE=""

rm -rf $LATEXINPUTLABELS
rm -rf $LABELFILE
newrow() {
CURRENTX=${ZEROPOSX}
CURRENTY=$1
SIZE=$2
CURRENTY=`echo "$CURRENTY + $YPITCH" | bc`
FREESPACEX=${MAXX}
FREESPACEY=`echo "${MAXY} - ${CURRENTY}" | bc`
}

createbarcode() {
OUT=$1
uuidgen | tr [[:upper:]] [[:lower:]] | tr -d '-'  | sed -e 's/\(.\{12\}\).*/\1/' | dmtxwrite -s 16x16 -o ${OUT}.png
}


while read ROW;
do
	echo "Processing Label named: " $ROW
	P1=`echo ${ROW} | cut -d '§' -f 1 | sed -e 's/^\ //;s/\ $//'`
	P2=`echo ${ROW} | cut -d '§' -f 2 | sed -e 's/^\ //;s/\ $//'`
	P3=`echo ${ROW} | cut -d '§' -f 3 | sed -e 's/^\ //;s/\ $//'`
	P4=`echo ${ROW} | cut -d '§' -f 4 | sed -e 's/^\ //;s/\ $//'`
	P5=`echo ${ROW} | cut -d '§' -f 5 | sed -e 's/^\ //;s/\ $//'`
	echo "DEBUG: "$P1"|"$P2"|"$P3"|"$P4"|"$P5
	if [ "${P5}" == "1" ]; then
		LATEXTEMPLATE="onelabel-size1"
	fi
	if [ "${P5}" == "2" ]; then
		LATEXTEMPLATE="onelabel-size2"
	fi
	if [ "${P5}" == "3" ]; then
		LATEXTEMPLATE="onelabel-size3"
	fi
	if [ "${P5}" == "b" ]; then
		LATEXTEMPLATE="onelabel-barcodeOnly"
	fi
	echo "Latextemplate is: ${LATEXTEMPLATE}"
	createbarcode barcodes/barcode_${COUNTER}
	LATEXCOMMAND="pdflatex \newcommand{\labelp}{$P1}\newcommand{\labelpp}{$P2}\newcommand{\labelppp}{$P3}\newcommand{\labelpppp}{$P4}\newcommand{\labelbarcode}{\includegraphics[width=6.5mm]{barcodes/barcode_${COUNTER}.png}}\input{\"${LATEXTEMPLATE}.tex\"}"
	echo "Doing Command ${LATEXCOMMAND}"
	echo ${LATEXCOMMAND} >> latexcommandfile.txt
	${LATEXCOMMAND}
	
	echo "Moving output to "singlelabels/label_"${COUNTER}".pdf
	mv ${LATEXTEMPLATE}.pdf singlelabels/label_"${COUNTER}".pdf
	echo ${P5} "§" singlelabels/label_"${COUNTER}".pdf >> $LABELFILE
	COUNTER=`expr $COUNTER + 1`
done < ${INPUTFILE}

echo "Read in file ${INPUTFILE}"

CURRENTX=${ZEROPOSX}
CURRENTY=${ZEROPOSY}
FREESPACEX=${MAXX}
FREESPACEY=${MAXY}
if [ "A" == "A" ] ; then
while read ROW;
do
	LABELSIZE=`echo ${ROW} | cut -d '§' -f 1 | sed -e 's/^\ //;s/\ $//'`
	LABELPDF=`echo ${ROW} | cut -d '§' -f 2 | sed -e 's/^\ //;s/\ $//'`
	echo "Creating Latex-Command for Label in " $LABELPDF 
		if [ "${LABELSIZE}" == "1" ]; then
		if [ ${FREESPACEX} -le $XPITCHSIZE1 ];then
		newrow $CURRENTY $LABELSIZE
		fi
	fi
	if [ "${LABELSIZE}" == "2" ]; then
		if [ ${FREESPACEX} -le $XPITCHSIZE2 ];then
		newrow $CURRENTY $LABELSIZE
		fi
	fi
	if [ "${LABELSIZE}" == "b" ]; then
		if [ ${FREESPACEX} -le $XPITCHSIZEB ];then
		newrow $CURRENTY $LABELSIZE
		fi
	fi
	
	echo "\path(${CURRENTX}mm,${CURRENTY}mm) node[right]{\includegraphics{$LABELPDF}};" >> $LATEXINPUTLABELS
	if [ "${LABELSIZE}" == "1" ];then
		CURRENTX=`echo "${CURRENTX}+${XPITCHSIZE1}" | bc`
		FREESPACEX=`echo "${FREESPACEX}-${XPITCHSIZE1}" | bc`
	elif [ "${LABELSIZE}" == "b" ];then
		CURRENTX=`echo "${CURRENTX}+${XPITCHSIZEB}" | bc`
		FREESPACEX=`echo "${FREESPACEX}-${XPITCHSIZEB}" | bc`
	else
		CURRENTX=`echo "${CURRENTX}+${XPITCHSIZE2}" | bc`
		FREESPACEX=`echo "${FREESPACEX}-${XPITCHSIZE2}" | bc`
	fi
done < $LABELFILE
echo "RUNNING COMMAND: "
echo "pdflatex \newcommand{\includelabels}{\input{$LATEXINPUTLABELS}}\input{alllabels.tex}"
pdflatex "\newcommand{\includelabels}{\input{$LATEXINPUTLABELS}}\input{alllabels.tex}"
fi
